baseurl = "https://example.org"
title = "HPCAT"
theme = "universal"
#themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "Sebastian Foubert"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "News"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "Publications"
    identifier = "publications"
    url  = "/publications/"
    weight = 3

[[menu.main]]
    name = "Director"
    identifier = "Professor"
    url  = "/professor/"
    weight = 4

[[menu.main]]
    name = "Open Positions"
    identifier = "positions"
    url  = "/positions/"
    weight = 5

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/hpcat"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "GWU ECE"
    url = "https://www.ece.seas.gwu.edu/"
    pre = "<i class='fa fa-2x fa-bolt'></i>"

#[[menu.topbar]]
#    weight = 3
#    name = "Twitter"
#    url = "http://twitter.com"
#    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:louri@gwu.edu"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Sebastian Foubert"
    defaultKeywords = ["HPCAT", "Louri"]
    defaultDescription = "High Performance Computing Architectures & Technologies Lab"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "louri@gwu.com"

    about_us = "<p>High Performance Computing Architectures & Technologies Lab</p>"
    copyright = "Copyright (c) 2017 - 2018, HPCAT; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/hpcat_logo.png"
    address = """<p><strong>Ahmed Louri, Ph.D.</strong>
        <br>David and Marilyn Endowed Chair Professor of ECE
        <br>Department of Electrical and Computer Enginnering
        <br>The George Washinton University
        <br>800 22nd Street NW, Room 5580
        <br>Washington, DC
        <br>
        <strong>United States of America</strong>
      </p>
      """
    latitude = "38.89992"
    longitude = "77.04943029999998"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs"></p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "HPCAT Members"
    #subtitle = "Motivated and Seeking KNowledge "
    subtitle = "" 

[params.see_more]
    enable = true
    icon = "fa fa-desktop"
    title = "Do you want to be part of this?"
    subtitle = "We are always seeking talented researchers that are ambitious and want to know more"
    link_url = "/positions/"
    link_text = "Open Positions"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Partners"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "NEWS"
    subtitle = "We are always striving to improve. The members of the High Performance Computing Architectures & Technologies are always on the move from publishing papers to making ground breaking discoveries that will shape the world of tomorrow."
